import { NewsItem } from './newsService';

export const MOCK_NEWS_ITEMS: NewsItem[] = [
  {
    id: 'demo_1',
    title: 'Supreme Court asks SBI to disclose electoral bond data within 3 days',
    description: 'The court directed the bank to submit purchase details to the Election Commission, sharpening scrutiny of political funding transparency.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop',
    publishedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    channelName: 'The Wire',
    channelId: 'UChWtJey46brNr7qHQpN6KLQ',
    channelType: 'journalism',
    language: 'en',
    source: 'rss',
    trustLevel: 'verified',
    hasDoc: true,
    docUrl: 'https://pib.gov.in',
    category: 'accountability',
    url: 'https://thewire.in',
    aiSummary: '• Court wants faster disclosure of electoral bond records.\n• The Election Commission is expected to receive detailed data.\n• Citizens should follow official filings for confirmed numbers.',
  },
  {
    id: 'demo_2',
    title: 'Farmers resume march near Delhi border over MSP guarantee',
    description: 'Farmer groups from Punjab and Haryana renewed their demand for a legal guarantee on MSP as police increased deployment near border points.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop',
    videoId: 'dQw4w9WgXcQ',
    publishedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    channelName: 'Ravish Kumar',
    channelId: 'UC0yXUUIaPVAqZLgRjvtMftw',
    channelType: 'ground_reality',
    language: 'hi',
    source: 'youtube',
    trustLevel: 'youtube',
    hasDoc: false,
    category: 'accountability',
    url: 'https://youtube.com',
    aiSummary: '• किसान MSP की कानूनी गारंटी की मांग दोहरा रहे हैं.\n• दिल्ली सीमा पर सुरक्षा बढ़ाई गई है.\n• स्थानीय यात्रियों को ट्रैफिक अपडेट देखते रहना चाहिए.',
  },
  {
    id: 'demo_3',
    title: 'Fact check: Viral free electricity claim is misleading',
    description: 'A widely shared message claiming free electricity for all households uses an old political clip without the necessary context.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&auto=format&fit=crop',
    publishedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    channelName: 'Alt News',
    channelId: 'UCdDjoZAtt6PjQKAbr2FTOAQ',
    channelType: 'fact_check',
    language: 'en',
    source: 'rss',
    trustLevel: 'verified',
    hasDoc: true,
    category: 'fact_check',
    url: 'https://altnews.in',
    aiSummary: '• The viral claim needs context and is not a confirmed national policy.\n• The clip appears to be old.\n• Check official state and central notices before sharing.',
  },
  {
    id: 'demo_4',
    title: 'Manipur crisis: Ground reports track continuing displacement',
    description: 'Independent reporters continue to document relief camps, security concerns, and the need for sustained national attention.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1484557985045-edf25e08da73?w=800&auto=format&fit=crop',
    videoId: 'dQw4w9WgXcQ',
    publishedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    channelName: 'Unfiltered by Samdish',
    channelId: 'UCxS1tE3hXN8YJ4vB71_V12Q',
    channelType: 'investigative',
    language: 'en',
    source: 'youtube',
    trustLevel: 'youtube',
    hasDoc: true,
    category: 'accountability',
    url: 'https://youtube.com',
    aiSummary: '• Displacement and safety concerns remain serious.\n• Ground reports can reveal gaps missed by daily headlines.\n• Follow multiple verified sources for updates.',
  },
  {
    id: 'demo_5',
    title: 'RTI filing raises questions on large corporate tax waivers',
    description: 'Public finance campaigners say clearer disclosures are needed to understand the scale and rationale of tax concessions.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&auto=format&fit=crop',
    publishedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    channelName: 'Newslaundry',
    channelId: 'UC3x198n54q68_v242G51_pw',
    channelType: 'journalism',
    language: 'en',
    source: 'rss',
    trustLevel: 'verified',
    hasDoc: true,
    docUrl: 'https://rti.india.gov.in',
    category: 'accountability',
    url: 'https://newslaundry.com',
    aiSummary: '• RTI-based reporting questions corporate tax concessions.\n• Public records can improve fiscal transparency.\n• Exact figures should be checked against official replies.',
  },
  {
    id: 'demo_6',
    title: 'Explainer: What India’s data protection law means for citizens',
    description: 'The explainer looks at consent, exemptions, user rights, and how digital services may process personal data.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop',
    videoId: 'dQw4w9WgXcQ',
    publishedAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    channelName: 'Dhruv Rathee',
    channelId: 'UC-CSyyi47VX1lD9zyeABW3w',
    channelType: 'analysis',
    language: 'hi',
    source: 'youtube',
    trustLevel: 'youtube',
    hasDoc: true,
    category: 'technology',
    url: 'https://youtube.com',
    aiSummary: '• कानून डेटा इस्तेमाल के नियम तय करता है.\n• नागरिकों को सहमति और शिकायत अधिकार समझने चाहिए.\n• संवेदनशील डेटा साझा करने से पहले स्रोत जांचें.',
  },
  {
    id: 'demo_7',
    title: 'IMD issues heavy rain warning for parts of Maharashtra',
    description: 'Mumbai, Thane, Pune, and Raigad residents have been advised to avoid non-essential travel during intense rain spells.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=800&auto=format&fit=crop',
    publishedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    channelName: 'PIB India',
    channelId: 'pib_official',
    channelType: 'official',
    language: 'en',
    source: 'official',
    trustLevel: 'official',
    hasDoc: true,
    docUrl: 'https://mausam.imd.gov.in',
    category: 'state',
    url: 'https://pib.gov.in',
    aiSummary: '• Heavy rain may disrupt travel in several districts.\n• Residents should track official IMD alerts.\n• Avoid flooded roads and non-essential trips.',
  },
  {
    id: 'demo_8',
    title: 'Investigation examines police encounter deaths in Uttar Pradesh',
    description: 'The report reviews official records, family testimonies, and accountability questions around encounter cases.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1589391886645-d51941baf7fb?w=800&auto=format&fit=crop',
    publishedAt: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    channelName: 'The Quint',
    channelId: 'UCSaf-7p3J_N-02p7jHzm5tA',
    channelType: 'journalism',
    language: 'en',
    source: 'rss',
    trustLevel: 'verified',
    hasDoc: true,
    category: 'accountability',
    url: 'https://thequint.com',
    aiSummary: '• The investigation reviews encounter death records.\n• Families and officials present competing accounts.\n• Legal oversight and transparent data remain important.',
  },
];

export const MOCK_DOCUMENTS = [
  {
    id: 'doc_1',
    title: 'Digital Personal Data Protection Act, 2023',
    ministry: 'Ministry of Electronics and IT',
    date: '2023-08-11',
    type: 'Act',
    fileSize: '2.1 MB',
    url: 'https://www.meity.gov.in/writereaddata/files/Digital%20Personal%20Data%20Protection%20Act%202023.pdf',
    summary: 'Sets rules for collection, processing, and storage of personal digital data.',
    category: 'law',
    language: 'en',
  },
  {
    id: 'doc_2',
    title: 'PM-KISAN Scheme Guidelines',
    ministry: 'Ministry of Agriculture',
    date: '2024-02-01',
    type: 'Government Order',
    fileSize: '890 KB',
    url: 'https://pmkisan.gov.in',
    summary: 'Explains eligibility and payment flow for direct income support to farmer families.',
    category: 'agriculture',
    language: 'hi',
  },
  {
    id: 'doc_3',
    title: "RTI Act 2005 - Citizen's Guide",
    ministry: 'Department of Personnel and Training',
    date: '2005-10-12',
    type: 'Act',
    fileSize: '1.5 MB',
    url: 'https://rti.india.gov.in',
    summary: 'Explains how citizens can request government information and expected timelines.',
    category: 'rights',
    language: 'both',
  },
  {
    id: 'doc_4',
    title: 'Election Commission Model Code of Conduct',
    ministry: 'Election Commission of India',
    date: '2024-03-16',
    type: 'Guidelines',
    fileSize: '3.2 MB',
    url: 'https://eci.gov.in',
    summary: 'Rules for party, candidate, and government conduct during election periods.',
    category: 'election',
    language: 'en',
  },
];

export const MOCK_LIVE_STREAMS = [
  {
    id: 'live_1',
    title: 'Live: Press conference on market regulation report',
    streamer: 'Verified News Desk',
    viewers: 45230,
    thumbnail: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=800&auto=format&fit=crop',
    isLive: true,
    hasDoc: true,
    startedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    category: 'politics',
  },
  {
    id: 'live_2',
    title: 'Live: Delhi air quality ground report from ITO',
    streamer: 'Citizen Reporter Ananya',
    viewers: 8941,
    thumbnail: 'https://images.unsplash.com/photo-1585858229735-cd08d8978b7b?w=800&auto=format&fit=crop',
    isLive: true,
    hasDoc: false,
    startedAt: new Date(Date.now() - 1000 * 60 * 34).toISOString(),
    category: 'environment',
  },
];
