// JanSamachar — Mock Data for Demo Mode
// Realistic Indian news data for testing without API keys

import { NewsItem } from './newsService';

export const MOCK_NEWS_ITEMS: NewsItem[] = [
  {
    id: 'demo_1',
    title: 'SC Orders Disclosure of Electoral Bond Data Within 3 Days',
    description: "The Supreme Court has directed the State Bank of India to submit all electoral bond purchase data to the Election Commission, calling government's delay 'unacceptable'. This landmark ruling could reshape political funding transparency in India.",
    thumbnailUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop',
    publishedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 min ago
    channelName: 'The Wire',
    channelId: 'UChWtJey46brNr7qHQpN6KLQ',
    channelType: 'journalism',
    language: 'en',
    source: 'rss',
    trustLevel: 'verified',
    hasDoc: true,
    docUrl: 'https://pib.gov.in',
    category: 'accountability',
    url: 'https://thewire.in',
    aiSummary: '• SC orders SBI to release electoral bond data immediately\n• Government delay called unacceptable by Chief Justice\n• Political funding opacity may end with this ruling',
  },
  {
    id: 'demo_2',
    title: 'Farmers Protest Resumes Near Delhi Border — Ground Reality Report',
    description: 'Thousands of farmers from Punjab and Haryana have begun their march towards Delhi again, demanding legal guarantee for MSP. Ravish Kumar reports from the ground as police deploy water cannons at Shambhu border.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop',
    videoId: 'dQw4w9WgXcQ',
    publishedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(), // 1.5 hrs ago
    channelName: 'Ravish Kumar',
    channelId: 'UC0yXUUIaPVAqZLgRjvtMftw',
    channelType: 'ground_reality',
    language: 'hi',
    source: 'youtube',
    trustLevel: 'youtube',
    hasDoc: false,
    category: 'accountability',
    url: 'https://youtube.com',
    aiSummary: '• किसान फिर दिल्ली की ओर मार्च कर रहे हैं\n• MSP की कानूनी गारंटी की मांग जारी है\n• पुलिस ने शम्भू बॉर्डर पर पानी की बौछार की',
  },
  {
    id: 'demo_3',
    title: 'FAKE VIRAL: "Modi Announces Free Electricity for All" — Fact Check',
    description: 'A viral WhatsApp message claiming PM Modi announced free electricity for all Indian households is FALSE. Alt News traced the doctored screenshot to a 2022 state election speech taken wildly out of context.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&auto=format&fit=crop',
    publishedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    channelName: 'Alt News',
    channelId: 'UCdDjoZAtt6PjQKAbr2FTOAQ',
    channelType: 'fact_check',
    language: 'en',
    source: 'rss',
    trustLevel: 'verified',
    hasDoc: true,
    category: 'fact_check',
    url: 'https://altnews.in',
    aiSummary: '• Viral "free electricity" claim is completely FALSE\n• Screenshot doctored from a 2022 election speech\n• Share this fact-check to stop misinformation spreading',
  },
  {
    id: 'demo_4',
    title: 'Manipur Violence: 18 Months On — What the Cameras Don\'t Show',
    description: 'Unfiltered by Samdish investigates the continuing crisis in Manipur. With over 60,000 still displaced and 200+ dead, why has mainstream media gone silent? Exclusive ground reports from both communities.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1484557985045-edf25e08da73?w=800&auto=format&fit=crop',
    videoId: 'dQw4w9WgXcQ',
    publishedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    channelName: 'Unfiltered by Samdish',
    channelId: 'UCxS1tE3hXN8YJ4vB71_V12Q',
    channelType: 'investigative',
    language: 'en',
    source: 'youtube',
    trustLevel: 'youtube',
    hasDoc: true,
    category: 'accountability',
    url: 'https://youtube.com',
    aiSummary: '• Manipur crisis continues with 60,000+ displaced\n• Mainstream media coverage has drastically reduced\n• Both communities share exclusive accounts with Samdish',
  },
  {
    id: 'demo_5',
    title: 'RTI Reveals: ₹2 Lakh Crore Tax Waived for 50 Corporations in 2023',
    description: 'A Right to Information filing by activist Anjali Bhardwaj has revealed that the Income Tax department waived taxes worth ₹2.05 lakh crore for large corporations last fiscal year, even as small businesses face increased scrutiny.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&auto=format&fit=crop',
    publishedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    channelName: 'Newslaundry',
    channelId: 'UC3x198n54q68_v242G51_pw',
    channelType: 'journalism',
    language: 'en',
    source: 'rss',
    trustLevel: 'verified',
    hasDoc: true,
    docUrl: 'https://rti.india.gov.in',
    category: 'accountability',
    url: 'https://newslaundry.com',
    aiSummary: '• RTI reveals ₹2 lakh crore corporate tax waiver in 2023\n• 50 large corporations benefited while SMEs face scrutiny\n• Activist questions selective enforcement of tax laws',
  },
  {
    id: 'demo_6',
    title: 'Dhruv Rathee: "How Your Data Is Being Sold Without Consent" — Explained',
    description: 'A deep-dive analysis of the Digital Personal Data Protection Act 2023 and how the government has given itself broad exemptions. Dhruv explains in simple Hindi what this means for your WhatsApp, Aadhaar, and UPI data.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop',
    videoId: 'dQw4w9WgXcQ',
    publishedAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    channelName: 'Dhruv Rathee',
    channelId: 'UC-CSyyi47VX1lD9zyeABW3w',
    channelType: 'analysis',
    language: 'hi',
    source: 'youtube',
    trustLevel: 'youtube',
    hasDoc: true,
    category: 'accountability',
    url: 'https://youtube.com',
    aiSummary: '• DPDP Act 2023 में सरकार ने खुद को व्यापक छूट दी है\n• आपका WhatsApp, Aadhaar और UPI डेटा खतरे में\n• आम नागरिकों को डेटा सुरक्षा का अधिकार कमजोर हुआ',
  },
  {
    id: 'demo_7',
    title: 'Weather Alert: Red Warning Issued for Mumbai, Pune — IMD',
    description: 'India Meteorological Department has issued a Red warning for extremely heavy rainfall in Mumbai, Thane, Pune, and Raigad districts. Citizens advised to avoid non-essential travel. NDRF teams deployed.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=800&auto=format&fit=crop',
    publishedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    channelName: 'PIB India',
    channelId: 'pib_official',
    channelType: 'official',
    language: 'en',
    source: 'official',
    trustLevel: 'official',
    hasDoc: true,
    docUrl: 'https://mausam.imd.gov.in',
    category: 'state',
    url: 'https://pib.gov.in',
    aiSummary: '• Mumbai, Pune में Red Alert — अत्यधिक भारी बारिश की चेतावनी\n• NDRF टीमें तैनात, घर से बाहर न निकलें\n• IMD ने अगले 24 घंटे बेहद खतरनाक बताए',
  },
  {
    id: 'demo_8',
    title: 'The Quint Investigation: UP Encounter Deaths — Who Is Accountable?',
    description: 'A year-long investigation by The Quint reveals that 183 people were killed in police encounters in Uttar Pradesh since 2017, with families alleging fake encounters. NHRC has taken cognizance of 6 cases.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop',
    publishedAt: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    channelName: 'The Quint',
    channelId: 'UCSaf-7p3J_N-02p7jHzm5tA',
    channelType: 'journalism',
    language: 'en',
    source: 'rss',
    trustLevel: 'verified',
    hasDoc: true,
    category: 'accountability',
    url: 'https://thequint.com',
    aiSummary: '• 183 encounter deaths in UP since 2017, families allege fake encounters\n• NHRC has taken cognizance of 6 cases\n• Accountability mechanisms need strengthening urgently',
  },
];

export const MOCK_DOCUMENTS = [
  {
    id: 'doc_1',
    title: 'Digital Personal Data Protection Act, 2023',
    ministry: 'Ministry of Electronics & IT',
    date: '2023-08-11',
    type: 'Act',
    fileSize: '2.1 MB',
    url: 'https://www.meity.gov.in/writereaddata/files/Digital%20Personal%20Data%20Protection%20Act%202023.pdf',
    summary: 'Governs collection, processing, and storage of personal digital data of Indian citizens.',
    category: 'law',
    language: 'en',
  },
  {
    id: 'doc_2',
    title: 'PM-KISAN Scheme Guidelines — Full Details',
    ministry: 'Ministry of Agriculture',
    date: '2024-02-01',
    type: 'Government Order',
    fileSize: '890 KB',
    url: 'https://pmkisan.gov.in',
    summary: 'Direct income support of ₹6,000/year to eligible farmer families in three installments.',
    category: 'agriculture',
    language: 'hi',
  },
  {
    id: 'doc_3',
    title: 'RTI Act 2005 — Citizen\'s Guide (Hindi + English)',
    ministry: 'Department of Personnel & Training',
    date: '2005-10-12',
    type: 'Act',
    fileSize: '1.5 MB',
    url: 'https://rti.india.gov.in',
    summary: 'Every citizen can request government information. Fee: ₹10. Response within 30 days.',
    category: 'rights',
    language: 'both',
  },
  {
    id: 'doc_4',
    title: 'Election Commission Model Code of Conduct — 2024',
    ministry: 'Election Commission of India',
    date: '2024-03-16',
    type: 'Guidelines',
    fileSize: '3.2 MB',
    url: 'https://eci.gov.in',
    summary: 'Rules governing party and candidate behavior during election period. Citizens can report violations.',
    category: 'election',
    language: 'en',
  },
];

export const MOCK_LIVE_STREAMS = [
  {
    id: 'live_1',
    title: 'LIVE: Rahul Gandhi Press Conference on Adani Report',
    streamer: 'Congress Official',
    viewers: 45230,
    thumbnail: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=800',
    isLive: true,
    hasDoc: true,
    startedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    category: 'politics',
  },
  {
    id: 'live_2',
    title: 'LIVE: Delhi Air Quality Crisis — Ground Report from ITO',
    streamer: 'Citizen Reporter Ananya',
    viewers: 8941,
    thumbnail: 'https://images.unsplash.com/photo-1585858229735-cd08d8978b7b?w=800',
    isLive: true,
    hasDoc: false,
    startedAt: new Date(Date.now() - 1000 * 60 * 34).toISOString(),
    category: 'environment',
  },
];
